### ISSUE TITLE
Move to robotology

### ISSUE THREAD

**Issue by diegoferigo** [robotology/gym-ignition-models#19]
I think it's time to make this repository officially supported by our organization. We're already successfully using these models in our training pipelines with no major problems since few months now.

This repository is a dependency of gym-ignition, that is already inside robotology. It makes sense that also its dependencies will get the same maintenance policy.

cc @traversaro

**Comment by traversaro** [comment]
Yes, the only thing I have some doubts about is that I would prefer to have (even more) possibily outdated iCub models in robotology repos, but that is not a blocking problem.

**Comment by diegoferigo** [comment]
We discussed the topic in https://github.com/robotology/icub-models/issues/33 and we haven't yet found any long-term solution. Or, at least, I think we agreed that a single model + per-simulator tweaks using simulator-specific resources could be one of the possible long-term solutions. However, since then, no one has yet taken initiative to start such activity.

I think that in the moment we're going to progressively transition towards Ignition Gazebo (and I believe it's going to happen in the next 1 or 2 years), we have to face it anyway. We won't drop Gazebo Classic support.

Although, for the moment, the modification of this iCub model are not major (#1, #9, #15), and gym-ignition-models has reasons to exist in the long run even without the iCub model.

**Comment by traversaro** [comment]
Ack, I don't think in any case there is a big difference if the repo is in dic-iit or robotology. However, just to clarify: the problem that I fear is not that there is the same model (with small modifications) in different repos **per se**, but that the process of converting the  model of iCub to be stored in this repo is not automatic, and so in the future the model in this repo could be outdated  w.r.t. to the one generated with automatic generation in  https://github.com/robotology/icub-models .

**Comment by traversaro** [comment]
Done, feel free to close.

**Comment by diegoferigo** [comment]
> Done, feel free to close.

Awesome, thanks!

> in the future the model in this repo could be outdated w.r.t. to the one generated with automatic generation in https://github.com/robotology/icub-models

If for some reason in the future this repository becomes unmaintained and it does no longer meet enough requirements to stay in `robotology`, we can always move it to either `robotology-legacy` or "downgrade" it to `robotology-playground`, right?

**Comment by traversaro** [comment]
> > in the future the model in this repo could be outdated w.r.t. to the one generated with automatic generation in https://github.com/robotology/icub-models
> 
> If for some reason in the future this repository becomes unmaintained and it does no longer meet enough requirements to stay in `robotology`, we can always move it to either `robotology-legacy` or "downgrade" it to `robotology-playground`, right?

Yes.
