### ISSUE TITLE
iCubGazeboV2_5 meshes directory

### ISSUE THREAD

**Issue by Reaper151** [robotology/gym-ignition-models#21]
I think meshes for iCubGazeboV2_5 which in folder `gym_ignition_models/meshes/iCubGazeboV2_5/simmechanics` should move to `gym_ignition_models/iCubGazeboV2_5/meshes/simmechanics` to properly reference.

**Comment by diegoferigo** [comment]
Mesh folders are shared for multiple iCub urdf files and they are stored in a separated folder. This repository is not meant to be used as it is, and it should be installed with pip [as documented](https://github.com/robotology/gym-ignition-models#setup). Setuptools will install the files with the proper folder structure.
